version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/app
  
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_USER: 'tester'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'database_dev'
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

# to not store with project
# volumes:
#   mysqldata: {}